[package]
name = "polygon_rl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.7.0"
#ssim = {path = "ssim"}
ndarray = "0.15.6"
opencv = "0.68.0"
